### ISSUE TITLE
PHP Fatal error:  Arrays are not allowed in class constants 

### ISSUE THREAD

**Issue by kilmarac** [compucorp/civihr-installer#16]
After significant difficulty getting this to run, there are a couple things I had to do. 

1) I HAD to run the mysql user as Root with no password or it would fail out at the mysql stage. 
2) I had to increase the max allowed packet to 100M or it would timeout. 

I finally got into the site and the first connection failed.    Second it loaded and I logged in and got "/oboardingform is not found"

Finally after running updates, I got the following:

mod_fcgid: stderr: PHP Fatal error:  Arrays are not allowed in class constants in public_html/sites/all/modules/civihr-contrib-required/yoti/sdk/Yoti/YotiClient.php on line 35

Id really like to self host civihr, but so far having lots of difficulty.  Any insights?

**Comment by kilmarac** [comment]
Also got this one today
 Class 'Yoti\\InsertQuery' not found in public_html/includes/database/mysql/query.inc on line 14

**Comment by luutan04** [comment]
I installed successful, but when login I see this message: The requested page "/onboarding-form" could not be found.
attached image: https://www.screencast.com/t/lk9tGXFduEHR

How can I fix this issue? Thanks

**Comment by davialexandre** [comment]
Thanks for reporting these issues @luutan04 and @kilmarac. The script has just been updated. Can you please pull the latest version, try to create a new site and confirm that the issues have been fixed?

**Comment by luutan04** [comment]
Yes, the onboarding-form issue is fixed.
 But on this form, I got an error message "Notice: Undefined offset: 1 in wf_crm_enabled_fields() (line 457 of /var/www/html/civihr/sites/all/modules/contrib/webform_civicrm/includes/utils.inc).
"
![onboarding_form](https://user-images.githubusercontent.com/26811855/34318000-0a8cb214-e7ef-11e7-91da-d9426b69ac76.png)

**Comment by davialexandre** [comment]
@luutan04 This is a known error and it will be fixed soon. However, it doesn't affect any of CiviHR's functionalities. For now, you can hide it by either setting PHP to not display errors or to not report E_NOTICE errors.

Give the original issue has been fixed, I'm closing this. Thank you both for reporting it
