### ISSUE TITLE
Stuck on login

### ISSUE THREAD

**Issue by EnabIT** [compucorp/civihr-installer#37]
Hi,
I've followed the stated steps as you mentioned it on local machine and modified the apache conf file and correct the DNS.
when I'm trying to login with given password after installation finished it reload login page.

Is there anything you could help me with it?

**Comment by davialexandre** [comment]
@EnabIT Do you have mod_rewrite enabled in Apache? The only time I've seen a error similar to this, it was due to the module being disabled.

Other than that, try checking your CiviCRM and apache error logs for more details

**Comment by EnabIT** [comment]
Thanks for your help, it works
I forget to enable it.
